### ISSUE TITLE
yii2-app-advanced error

### ISSUE THREAD

**Issue by zsd-it** [tsingsun/yii2-daemon#13]
错误信息:
```
An Error occurred while handling another error:
worker:#0yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /data/wwwroot/note-swoole/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/di/ApplicationDecorator.php(41): yii\base\Module->runAction('site/error')
#1 /data/wwwroot/note-swoole/vendor/yiisoft/yii2/web/ErrorHandler.php(108): tsingsun\swoole\di\ApplicationDecorator->__call('runAction', Array)
#2 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/web/ErrorHandler.php(55): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#3 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/bootstrap/WebApp.php(65): tsingsun\swoole\web\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#4 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/bootstrap/BaseBootstrap.php(124): tsingsun\swoole\bootstrap\WebApp->handleRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#5 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/server/HttpServer.php(40): tsingsun\swoole\bootstrap\BaseBootstrap->onRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#6 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "site/index". in /data/wwwroot/note-swoole/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /data/wwwroot/note-swoole/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('site/index', Array)
#1 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/bootstrap/WebApp.php(45): yii\web\Application->handleRequest(Object(tsingsun\swoole\web\Request))
#2 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/bootstrap/BaseBootstrap.php(124): tsingsun\swoole\bootstrap\WebApp->handleRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#3 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/server/HttpServer.php(40): tsingsun\swoole\bootstrap\BaseBootstrap->onRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /data/wwwroot/note-swoole/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/bootstrap/WebApp.php(45): yii\web\Application->handleRequest(Object(tsingsun\swoole\web\Request))
#1 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/bootstrap/BaseBootstrap.php(124): tsingsun\swoole\bootstrap\WebApp->handleRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#2 /data/wwwroot/note-swoole/vendor/tsingsun/yii2-swoole/src/server/HttpServer.php(40): tsingsun\swoole\bootstrap\BaseBootstrap->onRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#3 {main}
```

PHP version
```
PHP 7.1.8 (cli) (built: May 14 2019 17:59:44) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

swoole version
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.3
Built => May 16 2019 20:01:37
coroutine => enabled
kqueue => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144
```

**Comment by zsd-it** [comment]
解决了

when I see  bootstrap , I found, add the following code can solve this question.

```
        Yii::setAlias('@webroot', WEBROOT);
        Yii::setAlias('@web', '/');
        Yii::setAlias('@common', dirname(__DIR__));
        Yii::setAlias('@frontend', dirname(dirname(__DIR__)) . '/frontend');
        Yii::setAlias('@backend', dirname(dirname(__DIR__)) . '/backend');
        Yii::setAlias('@console', dirname(dirname(__DIR__)) . '/console');

```
